#############################################################################################################################################################################
#############################################################################################################################################################################
#############################################################################################################################################################################

# DOCUMENTATION FOR THE PROGRAM: effective_angle.py
# BY: JACOB R. SPRAGUE

# THIS PROGRAM USES THE SOFTWARE PACKAGE "MIT PHOTONIC BANDS" (MPB).
# THIS PROGRAM COMPUTES THE BAND STRUCTURES FOR THE "GEOMETRY" (DEFINED BELOW) OVER A USER-SPECIFIED LIST OF KZ, WHERE KZ IS THE COMPONENT OF THE WAVE-VECTOR PARALLEL TO THE FIBER.
# GEOMETRY: AN L X L  SQUARE LATTICE OF SQUARE HOLES (L HOLES ON EACH SIDE) W/ FILLING FRACTION f, AND A SOLID CORE W/ SQUARE CROSS-SECTION IN THE CENTER.
# WE TAKE THE LATTICE CONSTANT "a" TO BE TWICE THE DISTANCE BETWEEN THE CENTERS OF ADJACENT HOLES; IF THE DISTANCE BETWEEN ADJACENT HOLES IS SET EQUAL TO 1, THEN THE LATTICE CONSTANT a = 2
# DUE TO THE SCALE-INVARIANCE OF PHOTONIC CRYSTALS, WE SET THE SCALE OF THE PHOTONIC CRYSTAL TO BE 100 nm; i.e. THE DISTANCE BETWEEN ADJACENT HOLES = 100 nm, AND a = 200 nm.


# EACH BAND STRUCTURE COMPUTED HAS ITS OWN VALUE OF KZ; FOR EXAMPLE, IF THE LIST OF KZ IS {0, 0.1, 0.2, 0.3}, THEN FOUR BAND STRUCTURES WILL BE COMPUTED: THE FIRST STRUCTURE WILL BE FOR KZ = 0, THE SECOND WILL BE FOR KZ = 0.1, etc.

# THE USER INPUTS: L, f, THE NUMBER OF BANDS TO BE CALCULATED, THE RELATIVE PERMITTIVITIES OF THE PHOTONIC CRYSTAL MATERIAL AND THE CORE, A LOWER BOUND ON KZ, AN UPPER BOUND ON KZ, AND AN INCREMENT SIZE FOR CREATING A LIST OF KZ VALUES FROM KZ_LOWER TO KZ_UPPER IN STEPS OF 'INCREMENT'.
# THE USER HAS THE OPTION TO CALCULATE THE BAND STRUCTURES WITH OR WITHOUT THE CORE PRESENT IN THE FIBER.
# THE USER HAS THE OPTION TO USE MPB'S "TARGETED EIGENSOLVER" TO SOLVE FOR THE BANDS NEAREST TO A SPECIFIED FREQUENCY (MUST BE SPECIFIED IN THz).
# WARNING: THE TARGETED EIGENSOLVER CONVERGES MUCH MORE SLOWLY THAN THE ORDINARY EIGENSOLVER, SO RUNNING THE PROGRAM W/ THE TARGETED EIGENSOLVER TAKES MUCH LONGER.
# THE USER IS GIVEN THE OPTION TO START OVER IN CASE THEY WANT TO CHANGE ANY OF THE PARAMETERS OF THE SIMULATION.

# THE BAND STRUCTURE DATA, WHICH CONSISTS OF A SET OF EIGEN-FREQUENCIES CALCULATED AT SEVERAL POINTS ALONG THE IRREDUCIBLE BRILLOUIN ZONE, ARE USED TO COMPUTE THE OFF-AXIS ANGLES (i.e. ANGLE W/ RESPECT TO THE FIBER AXIS, HENCEFORTH REFERRED TO AS 'THETA') AT WHICH THE EIGENMODES CANNOT PROPAGATE. A RANGE OF THETA AT WHICH THE MODES CANNOT PROPAGATE IS CALLED AN "ANGLE-GAP".
# THE FORMULA FOR COMPUTING THETA AS A FUNCTION OF FREQUENCY IS GIVEN IN THE PAPER "OFF-PLANE ANGLE DEPENDENCE OF PHOTONIC BAND GAP IN A TWO-DIMENSIONAL PHOTONIC CRYSTAL" (FENG & ARAKAWA).
# THE FENG & ARAWAKA FORMULA INVOLVES AN "EFFECTIVE REFRACTIVE INDEX." FENG & ARAWAKA ALSO PROVIDE A FORMULA FOR COMPUTING THE EFFECTIVE REFRACTIVE INDEX OF A PHOTONIC CRYSTAL IN TERMS OF THE FILLING FRACTION AND THE RELATIVE PERMITTIVITIES:

# EFFECTIVE REFRACTIVE INDEX = SQRT{f*permittivity of air  +  (1 - f)*permittivity of PC material}  (FENG  & ARAKAWA)

# SINCE WE HAVE A SOLID CORE IN THE CENTER OF OUR PHOTONIC CRYSTAL, WE HAVE TO MODIFY THE FENG & ARAKAWA FORMULA.
# BECAUSE THE CORE HAS A SQUARE CROSS-SECTION AND IS CENTRALLY-LOCATED IN THE FIBER, WE ASSUME THAT IT CAN BE TREATED AS IF IT WERE SUBDIVIDED INTO EQUAL-SIZE SQUARE PIECES AND UNIFORMLY-DISTRIBUTED THROUGHOUT THE CROSS-SECTION OF THE FIBER, GIVING RISE TO ITS OWN "FILLING FRACTION", WHICH WE REFER TO AS f_core:

# EFFECTIVE REFRACTIVE INDEX = SQRT{f*permittivity of air  +  (1 - f)*permittivity of PC material + f_core*permittivity of core  +  (1 - f_core)*permittivity of PC material}  (MODIFIED FORMULA)

# AFTER THE PROGRAM FINISHES COMPUTING ALL THE BAND DIAGRAMS, AN IMAGE OF THE CROSS-SECTION OF THE FIBER IS DISPLAYED.
# FIVE DIAGRAMS ARE PRODUCED:
# 1.) A 3D PLOT OF ALL THE BAND STRUCTURES OVER ALL VALUES OF KZ.
# 2.) A PLOT OF THE THETA-VALUES COMPUTED AT THE UPPER AND LOWER BOUNDARIES OF EACH BAND-GAP FOR EACH BAND-STRUCTURE AS A FUNCTION OF FREQUENCY; FOR EACH BAND STRUCTURE (i.e. FOR EACH VALUE OF KZ), THE CORRESPONDING POINTS ON THE GRAPH ARE CONNECTED BY A RED CURVE. 
# 3.) THE PREVIOUS PLOT INVERTED SO THAT THETA IS ON THE X-AXIS AND FREQUENCY IS ON THE Y-AXIS.
# 4.) A PLOT OF THE ANGLE-GAPS AS A FUNCTION OF FREQUENCY. THE ANGLE-GAPS ARE SHADED IN RED. FOR THEIR CONVENIENCE, THE USER IS ASKED TO CHOOSE THE UPPER AND LOWER BOUNDS OF BOTH THE X- AND Y- AXES.
# 5.) THE USER GETS TO PICK A VALUE OF KZ FROM THE KZ LIST AND SEE THE BAND STRUCTURE CORRESPONDING TO THAT VALUE.

# AFTER THE FIFTH DIAGRAM HAS BEEN CLOSED, THE USER HAS THE OPTION TO GO BACK AND SEE ALL OF THE DIAGRAMS AGAIN. THIS IS USEFUL IF, FOR EXAMPLE, ONE WANTS TO SAVE MULTIPLE BAND STRUCTURES FOR DIFFERENT VALUES OF KZ (i.e. DIAGRAM 5. IN THE LIST ABOVE).

# PRINTS RELEVANT INFORMATION,  SUCH AS THE NUMBER OF BANDS, THE PERMITTIVITIES OF THE MATERIALS, THE LATTICE CONSTANT, etc.


#############################################################################################################################################################################
#############################################################################################################################################################################
#############################################################################################################################################################################


























